apiVersion: apps/v1
kind: Deployment
metadata:
  name: kainskep-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        image: web:v4
        ports:
        - containerPort: 5000
